name: gh-integration

on:
  push:
  workflow_dispatch:
    inputs:
      TEST_ENDPOINT:
        description: "Endpoint for tests"
        required: true
        default: https://dev.github.com
      TEST_BROWSER:
        description: "Browser for tests"
        required: true
        default: chrome
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false


env:
  ALLURE_ENDPOINT: https://testing.testops.cloud
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}
  ALLURE_TESTPLAN_PATH: "./testplan.json"
  ALLURE_RESULTS: "build/allure-results"
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}

jobs:
  DownloadAllureCtl:
    name: main
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      allure-ci-env: ${{ steps.setup-allure-env.outputs.allure-ci-env }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: install and configure allurectl
        uses: allure-framework/setup-allurectl@v1
      - name: setup allure env
        id: setup-allure-env
        run: echo "allure-ci-env=$(bin/allurectl ci env --encode)" >> $GITHUB_OUTPUT
      
  all-tests-1:
    name: job1
    runs-on: ubuntu-latest
    needs: [ DownloadAllureCtl ]
    permissions: write-all
    env:
      ALLURE_CI_ENV: ${{needs.DownloadAllureCtl.outputs.allure-ci-env}}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install and configure allurectl
        uses: allure-framework/setup-allurectl@v1
      - name: Build with Gradle
        run: allurectl watch -- ./gradlew clean test --output ${ALLURE_RESULTS}
  all-tests-2:
    name: job2
    runs-on: ubuntu-latest
    needs: [ DownloadAllureCtl ]
    permissions: write-all
    env:
      ALLURE_CI_ENV: ${{needs.DownloadAllureCtl.outputs.allure-ci-env}}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install and configure allurectl
        uses: allure-framework/setup-allurectl@v1
      - name: Build with Gradle
        run: allurectl watch -- ./gradlew clean test --output ${ALLURE_RESULTS}

